### PR TITLE
Tighten up `saturating_` math checks

### LINKED ISSUE #1141: Saturating math -> checked math?
A number of places in soroban (fees, metering, ledger arithmetic) use saturating arithmetic to avoid the risk of over/underflow. This is _often_ correct (or harmless) but not always -- it also opens up the potential for two problems:

  1. Violating intended arithmetic identities (a - b makes c, then c + b should make a, but .. maybe now it doesn't)
  2. Hiding bugs (a - b underflows because we let b get too big .. but now we don't notice)

The next-best alternative is the _checked_ variants of all the currently-saturating arithmetic. I think in most of the places we use saturating, checked would work as well or better. We might want to add a helper trait that provides abbreviations for `checked_{add,sub,mul,div}(...).ok_or(Error::from_type_and_code(ScErrorType::Value, ScErrorCode::ArithDomain))`?

### PR DESCRIPTION
**Pull request by jayz22**
### What

Resolves #1141 

Several places benefit from changing `saturating_` to `checked_` math:
- `saturating_add(_mul)` on u32, saturation would be within possibility
- Some `saturating_sub` saturation would mean actual error, e.g index out of bound

In both cases, changing to `checked_` version means overflow errors are caught sooner. 

### Why

[TODO: Why this change is being made. Include any context required to understand the why.]

### Known limitations

[TODO or N/A]

### CODE REVIEW

File: soroban-env-host/src/budget/limits.rs [hunk 1]
```diff
@@ -96,7 +96,9 @@ impl DepthLimiter for BudgetImpl {
     // `leave` should be called in tandem with `enter` such that the depth
     // doesn't exceed the initial depth limit.
     fn leave(&mut self) -> Result<(), HostError> {
-        self.depth_limit = self.depth_limit.saturating_add(1);
+        self.depth_limit = self.depth_limit.checked_add(1).ok_or_else(|| {
+            Error::from_type_and_code(ScErrorType::Value, ScErrorCode::ArithDomain)
```
Comment (dmkozh) [inline soroban-env-host/src/budget/limits.rs:100]: This looks like an internal error to me - this could only ever occur if we call `leave` without `enter`.

File: soroban-env-host/src/host.rs [hunk 2]
```diff
@@ -2416,8 +2425,10 @@ impl VmCallerEnv for Host {
         let vnew = self.visit_obj(b, |hv: &ScBytes| {
             self.validate_index_lt_bound(i, hv.len())?;
             let mut vnew: Vec<u8> = hv.metered_clone(self)?.into();
-            // len > i has been verified above but use saturating_sub just in case
-            let n_elts = (hv.len() as u64).saturating_sub(i as u64);
+            // len > i has been verified above but use checked_sub just in case
+            let n_elts = (hv.len() as u64)
+                .checked_sub(i as u64)
+                .ok_or_else(|| self.err_arith_overflow())?;
```
Comment (dmkozh) [inline soroban-env-host/src/host.rs:2431]: This should be an internal error if we claim to guarantee the invariant in the comment above.

File: soroban-env-host/src/host/ledger_info_helper.rs [hunk 3]
```diff
@@ -16,16 +16,18 @@ impl Host {
                 self.with_ledger_info(|li: &LedgerInfo| Ok(li.min_persistent_entry_ttl))?
             }
         };
-        Ok(ledger_seq.saturating_add(min_live_until.saturating_sub(1)))
+        ledger_seq
+            .checked_add(min_live_until.saturating_sub(1))
+            .ok_or_else(|| self.err_arith_overflow())
```
Comment (dmkozh) [inline soroban-env-host/src/host/ledger_info_helper.rs:21]: This should probably be an internal error as well, as it means that we probably have a bad misconfiguration with huge min TTL.

File: soroban-env-host/src/host/ledger_info_helper.rs [hunk 4]
```diff
@@ -16,16 +16,18 @@ impl Host {
...
 
     pub(crate) fn max_live_until_ledger(&self) -> Result<u32, HostError> {
         self.with_ledger_info(|li| {
-            Ok(li
-                .sequence_number
+            li.sequence_number
                 // Entry can live for at most max_entry_live_until ledgers from
                 // now, counting the current one.
-                .saturating_add(li.max_entry_ttl.saturating_sub(1)))
+                .checked_add(li.max_entry_ttl.saturating_sub(1))
```
Comment (dmkozh) [inline soroban-env-host/src/host/ledger_info_helper.rs:29]: Same here, should be an internal error.

File: soroban-env-host/src/storage.rs [hunk 5]
```diff
@@ -422,8 +422,11 @@ impl Storage {
             ));
         }
 
-        let mut new_live_until =
-            host.with_ledger_info(|li| Ok(li.sequence_number.saturating_add(extend_to)))?;
+        let mut new_live_until = host.with_ledger_info(|li| {
+            li.sequence_number
+                .checked_add(extend_to)
+                .ok_or_else(|| host.err_arith_overflow())
```
Comment (dmkozh) [inline soroban-env-host/src/storage.rs:428]: Same, should be an internal error (we verify that the value is sane above, so this would only occur due to mis-configuration/bug).

File: soroban-env-host/src/host.rs (hunk 2 above)
Comment (jayz22) [reply soroban-env-host/src/host.rs]: Good point, fixed.

File: soroban-env-host/src/host/ledger_info_helper.rs (hunk 3 above)
Comment (jayz22) [reply soroban-env-host/src/host/ledger_info_helper.rs:21]: That wouldn't be "internal" error though. Like, if someone (say in their own test network) sets up a bad min TTL, it's not the host's internal logic bug. The error comes from "external" to the host and arithmetic overflow is the most accurate code to surface it back.

File: soroban-env-host/src/storage.rs (hunk 5 above)
Comment (jayz22) [reply soroban-env-host/src/storage.rs:428]: The `extend_to` is also passed externally, see reply above.

File: soroban-env-host/src/host/ledger_info_helper.rs (hunk 4 above)
Comment (jayz22) [reply soroban-env-host/src/host/ledger_info_helper.rs:29]: See reply above.

File: soroban-env-host/src/host/ledger_info_helper.rs (hunk 3 above)
Comment (dmkozh) [reply soroban-env-host/src/host/ledger_info_helper.rs:21]: Any error caused by misconfiguration is currently an internal error, which makes sense: we don't really want such errors to be recoverable and we do want to catch them as early as possible. Otherwise, the errors represent the conditions caused by the host function user input. I realize that philosophically you may say that network updates are also caused by the 'user' actions, but these are not the same 'user' as the regular Soroban user. In any case, even in your scenario it would be beneficial to return an internal error here - it will quickly identify the misconfiguration instead of hiding it behind a recoverable error. FWIW misconfiguration in this particular case will completely brick the network.

File: soroban-env-host/src/storage.rs (hunk 5 above)
Comment (dmkozh) [reply soroban-env-host/src/storage.rs:428]: `extend_to` is guarded by the configuration, and the misconfiguration should be an internal error.

File: soroban-env-host/src/host/ledger_info_helper.rs (hunk 3 above)
Comment (jayz22) [reply soroban-env-host/src/host/ledger_info_helper.rs]: Sounds good, updated to `InternalError` and added a comment.

File: soroban-env-host/src/host/ledger_info_helper.rs (hunk 4 above)
Comment (jayz22) [reply soroban-env-host/src/host/ledger_info_helper.rs:39]: Fixed.

File: soroban-env-host/src/storage.rs (hunk 5 above)
Comment (jayz22) [reply soroban-env-host/src/storage.rs]: Fixed.

**Review by graydon — APPROVED** [review]
