### PR TITLE
Fix map_keys and map_values

### LINKED ISSUE #405: map_keys panics with error "already borrowed: BorrowMutError"
A simple test on the SDK side calling the `map_keys` host function results in a panic with error message:
> already borrowed: BorrowMutError

```rust
let env = Env::default();
let map = map![&env, (0, 0), (1, 10), (2, 20), (3, 30), (4, 40)];
let keys = map.keys();
assert_eq!(keys, vec![&env, 0, 1, 2, 3, 4]);
```

```
thread 'map::test::test_keys' panicked at 'already borrowed: BorrowMutError', /Users/leighmcculloch/.cargo/git/checkouts/rs-soroban-env-230c62c6b1f3d3f1/c8bc71d/soroban-env-host/src/host.rs:619:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1805:5
   3: core::result::Result<T,E>::expect
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1055:23
   4: core::cell::RefCell<T>::borrow_mut
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/cell.rs:956:9
   5: soroban_env_host::host::Host::add_host_object
             at /Users/leighmcculloch/.cargo/git/checkouts/rs-soroban-env-230c62c6b1f3d3f1/c8bc71d/soroban-env-host/src/host.rs:617:9
```

The issue appears to occur on line 617 of this code:
https://github.com/stellar/rs-soroban-env/blob/3e9bd4632c9a5b860d1e961f2fb9645a8b2dceca/soroban-env-host/src/host.rs#L609-L624

This bug was discovered by @accordeiro.

### PR DESCRIPTION
**Pull request by leighmcculloch**
### What
Associate the vec object that is created in map_keys and map_values outside of visiting the original map.

### Why
Adding an object to the host while visiting another object causes a BorrowMut error.

Close #405

### CODE REVIEW

File: soroban-env-host/src/host.rs [hunk 1]
```diff
@@ -1120,25 +1120,25 @@ impl CheckedEnv for Host {
...
-                vec = self.vec_push_back(vec, k.to_raw())?;
+        let vec = self.visit_obj(m, |hm: &HostMap| {
+            let mut vec = HostVec::new(self.0.budget.clone())?;
+            for k in hm.keys()?.cloned() {
+                vec.push_back(k)?;
             }
             Ok(vec)
-        })
+        })?;
+        Ok(self.add_host_object(vec)?.into())
```
Comment (leighmcculloch) [inline soroban-env-host/src/host.rs:1130]: @graydon @jayz22 There may be a better way to implement this, but this is what I could muster. Review appreciated.

Comment (jayz22) [reply soroban-env-host/src/host.rs:1130]: Thanks @leighmcculloch for fixing! This looks good to me.
