### PR TITLE
Remove ConversionError from ScVal/Val conversions

### LINKED ISSUE #1046: too much use of ConversionError
There are a lot of `TryFromVal` impls in env-common that use `type Error = ConversionError` where they really ought to use `type Error = crate::Error` and plumb through the env's error. In the current situation, all host errors get collapsed into `ConversionError` which then gets converted up to `Error(ScErrorType::Value, ScErrorCode::UnexpectedType)` which is really not what a lot of host errors are. This is a very misleading way of learning you ran out of gas in the middle of a conversion, for example.

Unfortunately these signatures are deeply intertwined with code all through the host and, especially, the SDK; if we change them we break a ton of downstream stuff. It would be good to coordinate a change to these someday. They were set to ConversionError for expedience, with merging the error types left as future work during [the last round of reform to TryFromVal](https://github.com/stellar/rs-soroban-env/pull/628) and we've just not found time to go back and finish the job.

### LINKED ISSUE #1076: TryFromVal<E, Val> for ScVal collapses Errors
This is just residue from earlier work that never got finished: in env-common, in convert.rs, when we call object.try_into_val in `TryFromVal<E, Val> for ScVal`, we collapse any errors we got via map_err into ConversionError. This is one of the cases where it'd really be better for the impl's Error type to be Error not ConversionError but it's fairly invasive and involves SDK changes to fix.

This is probably not going to make the cut for mainnet, there's too much else to do and it's not the most likely type of failure to even occur in the first place. But it'd be better to try. We might be able to fix this in a backward-compatible fashion if we're willing to version-gate it or if nobody triggers the difference.

### PR DESCRIPTION
**Pull request by graydon**
This is as minimal a change as I could manage to remove `ConversionError` from the ScVal/Val conversion paths, allowing `Error` codes to flow through (eg. invalid inputs or, more importantly, budget exhaustion or the like).

This _is_ observable, and it _does_ break public API (contra semver) so .. we should be sure if we want to do it. It also has a corresponding SDK change I'll post shortly. But I think it's very worthwhile and one of the last bugs I really wanted to fix before locking things down. Didn't think we'd be able to, but it looks like enough got cleaned up in the meantime that it was possible.

Fixes #1076 
Fixes #1046

### CODE REVIEW

**Review by jayz22 — APPROVED** [review]

**Review by sisuresh — APPROVED** [review]

File: soroban-env-host/src/host/conversion.rs [hunk 1]
```diff
@@ -521,11 +518,11 @@ impl Host {
...
             | ScVal::LedgerKeyNonce(_)
             | ScVal::ContractInstance(_)
-            | ScVal::LedgerKeyContractInstance => Err(err!(
-                self,
-                (ScErrorType::Value, ScErrorCode::InternalError),
+            | ScVal::LedgerKeyContractInstance => Err(self.err(
+                ScErrorType::Value,
+                ScErrorCode::InternalError,
                 "converting ScValObjRef on non-object ScVal type",
-                *val
```
Comment (sisuresh) [inline soroban-env-host/src/host/conversion.rs:528]: Is there a reason for not including the val in the error?

Comment (graydon) [reply soroban-env-host/src/host/conversion.rs:528]: Yeah, it's not actually a Val, it's an ScVal, which was only being handled by the `err!` macro that tries to re-convert it to Val via DebugArg. First of all this won't even work -- it's wasted work in this case as we know for sure the ScVal _isn't_ convertable to a Val -- and second of all to even make the types work requires a bunch more generic-constraint acrobatics beyond what I'm already doing in this PR, and it just didn't seem worth the effort for a thing-that-doesn't-work-anyway.
