### PR TITLE
Stop treating storage errors as missing entries

### LINKED ISSUE #834: Handle storage errors properly in token logic
Currently built-in token contract implementation incorrectly makes and assumption that the storage returns an error when entry is missing. For example, balance check is done like so:

```rust
if let Ok(raw_balance) = e.get_contract_data(key.try_into_val(e)?) {
```
where the failure is handled gracefully. However, storage returns different errors when the entry is missing and the entry hasn't been declared in the footprint, so when entry is missing from the footprint the result would be as if entry simply doesn't exist, which is a bug.

We should create more user-friendly wrappers for the storage that would return `Result<Option<T>>`, in order to check for the item presence as intended and use it everywhere we deal with storage in the host.

### PR DESCRIPTION
**Pull request by sisuresh**
### What

Resolves #834

### CODE REVIEW

File: soroban-env-host/src/native_contract/token/allowance.rs [hunk 1]
```diff
@@ -63,23 +66,28 @@ pub fn write_allowance(
...
-                },
-                None,
-            ))
-        } else {
-            None
+                let old_expiration = updated_allowance.expiration_ledger;
+                updated_allowance.expiration_ledger = expiration;
+                Some((updated_allowance, Some(old_expiration)))
+            }
+            None => {
```
Comment (dmkozh) [inline soroban-env-host/src/native_contract/token/allowance.rs:78]: nit: this could be somewhat simplified to `if let Some(allowance) = ... {} else if amount > 0 {} else {}` (basically what you had before, but with `Some` instead of `Ok`). This applies to all the other places as well, but here I think it's especially beneficial as it reduces the nesting level.

**Review by dmkozh — APPROVED** [review]

File: soroban-env-host/src/native_contract/token/allowance.rs (hunk 1 above)
Comment (sisuresh) [reply soroban-env-host/src/native_contract/token/allowance.rs]: I wasn't sure if it was a good idea to encourage the use of `if let Some` in case someone in the future thinks `if let Ok` works here as well (since the bug is pretty subtle), but it's definitely the "rusty" thing to do, so I made the change.

Comment (dmkozh) [reply soroban-env-host/src/native_contract/token/allowance.rs]: I think the current interface is clear enough - the main caveat is really to use the helper instead of just `get`.
